# Generated by Django 3.0.8 on 2020-07-24 13:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Indicator',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=5, null=True)),
                ('name', models.CharField(max_length=50, null=True)),
                ('question', models.CharField(max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='IndicatorStatement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('statement', models.TextField(null=True)),
                ('indicator', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='curriculum.Indicator')),
            ],
        ),
    ]
