# Generated by Django 3.0.8 on 2020-07-24 18:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('curriculum', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='indicator',
            name='resource_document',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='indicator',
            name='resource_title',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.CreateModel(
            name='Resource',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, null=True)),
                ('document', models.TextField(null=True)),
                ('resource', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='resources', to='curriculum.IndicatorStatement')),
            ],
        ),
    ]
