# Generated by Django 3.0.3 on 2020-07-26 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('curriculum', '0002_auto_20200724_1839'),
    ]

    operations = [
        migrations.AlterField(
            model_name='indicator',
            name='question',
            field=models.CharField(max_length=500, null=True),
        ),
    ]
