# Generated by Django 3.0.3 on 2020-07-26 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('curriculum', '0004_auto_20200726_1401'),
    ]

    operations = [
        migrations.AlterField(
            model_name='indicator',
            name='resource_title',
            field=models.CharField(max_length=500, null=True),
        ),
    ]
