# Generated by Django 3.0.8 on 2020-07-26 22:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('curriculum', '0006_auto_20200726_2244'),
    ]

    operations = [
        migrations.RenameField(
            model_name='resource',
            old_name='resource',
            new_name='statement',
        ),
    ]
